# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SwiftBasics' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Kingfisher'

  # Pods for SwiftBasics

  target 'SwiftBasicsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
